# Generated by Django 5.1.7 on 2025-03-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branch_client_onlineevaluationguide_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='smart_lombard_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID пользователя в smartlombard'),
        ),
    ]
