# Generated by Django 5.1.7 on 2025-03-19 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_client_smart_lombard_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onlineevaluationguide',
            old_name='guide',
            new_name='text',
        ),
    ]
