# Generated by Django 5.1.7 on 2025-03-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_branch_options_alter_branch_work_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(default='111', max_length=255, verbose_name='Телефон менеджера'),
            preserve_default=False,
        ),
    ]
