# Generated by Django 5.1.7 on 2025-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_branch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address_url',
            field=models.URLField(default='https://google.com', verbose_name='Ссылка в яндекс картах'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='photo',
            field=models.ImageField(default='branches/default.png', upload_to='branches', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
