# Generated by Django 5.1.7 on 2025-06-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_branch_address_url_branch_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('url', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Наш сайт',
                'verbose_name_plural': 'Наши сайты',
            },
        ),
    ]
